import { Container } from '@chakra-ui/react'
import Head from 'next/head'
import Queues from '../components/Queues'

export default function Home() {
  return (
    <>
      <Head>
        <title>Văn Nghệ Karaoke</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container maxW='container.lg'>
          <Queues />
        </Container>
      </main>
    </>
  )
}
